export const SOCKET_EVENT = {
  NOTIFICATION_NEW: "NOTIFICATION_NEW",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_UPDATED: "TASK_UPDATED",
  MEETING_INVITED: "MEETING_INVITED",
  MEETING_UPDATED: "MEETING_UPDATED",
} as const;

export type SocketEvent = (typeof SOCKET_EVENT)[keyof typeof SOCKET_EVENT];
